# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Commands

# serve local:
# bash -c "jekyll serve"

# build for development:
# bash -c "jekyll build"

# build for production:
# bash -c "JEKYLL_ENV=production jekyll build"

title: Fabse.net baut ein 🏠
email: fabse.baut@fabse.net
description: > # this means to ignore newlines until "baseurl:"
  Wir haben uns als dreiköpfige Familie das Ziel gesetzt, ein Haus bauen zu lassen. 
  Auf diesem Blog kannst du uns dabei verfolgen und dich mit uns freuen, lernen oder auch weinen.

baseurl: "/baut" # the subpath of your site, e.g. /blog
url: "https://fabse.net" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%e. %B %Y"

permalink: pretty
google_analytics: UA-34726227-2

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-minifier

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
